### ISSUE TITLE
باگ

### ISSUE THREAD

**Issue by saveiran2023** [redpilllabs/GFIProxyProtector#10]
سلام روزتون بخیر
چندتا مشکل هست که باید اطلاع بدم

مورد اول در مورد دستور نحوه اجرا یه خط رو جا انداختین
باید بعد git clone یه cd GFIProxyProtector هم باشه تا اسکریپت اجرا بشه

دوما روی سرور یکی از شرکت ها که ابونتو 22.04 هستش نمی تونم اسکریپت رو فعال کنم

Adding cronjob to update xt_goip database

Increasing Connection State Tracking Limits
net.netfilter.nf_conntrack_max=61748
net.netfilter.nf_conntrack_max = 61748
<<< Finished kernel tuning! >>>
Getting the latest aggregated database
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  315k  100  315k    0     0   253k      0  0:00:01  0:00:01 --:--:-- 3444k
Converting the CIDR database to binary format...
Can't locate Net/CIDR/Lite.pm in @INC (you may need to install the Net::CIDR::Lite module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /usr/libexec/rainb0w/xt_geoip_build_agg line 9.
BEGIN failed--compilation aborted at /usr/libexec/rainb0w/xt_geoip_build_agg line 9.
xt_geoip               16384  0

Blocking OUTGOING connections to Iran
Could not open /usr/share/xt_geoip/IR.iv4: No such file or directory
iptables v1.8.7 (nf_tables): Could not read geoip database
Could not open /usr/share/xt_geoip/IR.iv6: No such file or directory
ip6tables v1.8.7 (nf_tables): Could not read geoip database
Could not open /usr/share/xt_geoip/IR.iv4: No such file or directory
iptables v1.8.7 (nf_tables): Could not read geoip database
Could not open /usr/share/xt_geoip/IR.iv6: No such file or directory
ip6tables v1.8.7 (nf_tables): Could not read geoip database

    #############################################################
    #                                                           #
    #                GFI Proxy Server Protection                #
    #                       Red Pill Labs                       #
    #                                                           #
    #      This is a subset of 'Rainb0w Proxy Installer'        #
    #        available at [github.com/redpilllabs/Rainb0w]            #
    #      and it utilizes the aggregated CIDR database         #
    #        available at [github.com/redpilllabs/GFIGeoIP]           #
    #                                                           #
    #############################################################

1) Block OUTGOING connections to Iran:    DEACTIVATED
2) Block ALL connections to/from China:   DEACTIVATED
0) Exit

Choose any option:

**Comment by saveiran2023** [comment]
sudo apt-get install -y libnet-cidr-lite-perl
این مدلی تونستم نصبش کنم و مشکل رو حل کنم

**Comment by kyochikuto** [comment]
با تشکر، به فهرست بسته های مورد نیاز اضافه شد. دستور git clone فقط بر روی سیستم عامل دبیان مورد نیازه و اوبونتو سرورها این بسته رو نصب دارند.

**Comment by saveiran2023** [comment]
دستتون درد نکنه
هنوز cd GFIProxyProtector
توی نحوه اجرا و قبل از ./run.sh اضافه نشده

**Comment by saveiran2023** [comment]
خیلی ممنونم ازتون
امکانش هستش متد های مسدود سازی بیشتری اضافه بشه؟
مثل مسدود سازی برای تمام کشور ها به غیر ایران
یا اگه بشه بهش دستی ای پی داد که همه رو به غیر اون ای پی خاص مسدود کنه
active probing داره به شدت پیشرفت می کنه

**Comment by kyochikuto** [comment]
دستور cd اضافه شد، مورد مسدودسازی هرچه غیر از ایران فعلا در اسکریپت Rainb0w هستش و برای این اسکریپت هم بررسی می‌کنم.

**Comment by kyochikuto** [comment]
> مثل مسدود سازی برای تمام کشور ها به غیر ایران 

در commit 52bf514 اضافه شد (بر روی سرور خام) امتحان کنید.

**Comment by saveiran2023** [comment]
عالی شد
روی سرور قبلی زدم بدون مشکل فعال شد

**Comment by kyochikuto** [comment]
خوبه، فقط خاطرنشان کنم با مسدود کردن ورودی غیرایرانی امکان renew کردن گواهی های TLS مختل میشه و باید دستی این حفاظت ها رو غیرفعال کرده گواهی ها رو بروز کنید دوباره فعال کنید. در روزهای اینده امکان مسدودسازی فقط چین رو دوباره اضافه میکنم و پیغام هشداری هم در این رابطه به اسکریپت اضافه میکنم.
