### ISSUE TITLE
دور زدن این اسکریپت

### ISSUE THREAD

**Issue by mshaterzadeh** [redpilllabs/GFIProxyProtector#11]
اول ممنون بابت زحماتی که کشیدین. آیا امکانش هست GFW با راه اندازی سرویسی روی کلادفلر و استفاده از آیپی های کلادفلر اقدام به کاوش سرورها بکنه و بتونه از این طریق این اسکریپت رو دور بزنه؟ چون ورودی سرو از طرف آیپی های کلادفلر باز هست. و یا اینکه بسته بودن آیپی از طرف چین برای GFW شک برانگیز نمیشه؟؟؟ ویا نمیشه کاری کرد مثل اسکریپت Rainbow حتی اگه درخواست مشکوکی وارد شد به سمت فایل های HTML فیک (وبسایت فیک) هدایت بشه؟

**Comment by kyochikuto** [comment]
درود
> آیا امکانش هست GFW با راه اندازی سرویسی روی کلادفلر و استفاده از آیپی های کلادفلر اقدام به کاوش سرورها بکنه

بله امکانش هست، اما مشاهدات نشان میدن که اکثرا از آی‌پی چینی و خارجی میان.

>  بسته بودن آیپی از طرف چین برای GFW شک برانگیز نمیشه؟؟؟

خیر، مسدود کردن آی‌پی های یک جغرافیا امری معمول در حیطه ی شبکه است.

> نمیشه کاری کرد مثل اسکریپت Rainbow حتی اگه درخواست مشکوکی وارد شد به سمت فایل های HTML فیک (وبسایت فیک) هدایت بشه؟

باید خودتون یک وب سرور nginx راه اندازی کنید، از وظایف این اسکریپت خارج است.

پیروز باشید.

**Comment by mshaterzadeh** [comment]
یه پیشنهاد : چرا گزینه ایرام اکسس وجو نداره؟ یعنی بلاک کردن تمام آیپی ها به غیر ایران و شبکه کلادفلر همزمان باهم هست. آیپی های کلادفلر برای ورودی سرور اصلا نیاز هست؟؟ من تو خود کلادفلر تمام ایپی های وردی به غیر ایران رو فیلتر کردم و فقط ایپی سرور خودم رو استثنا کردم که با فیلترشکن خودم بتونم پنلم رو باز کنم. فقط سوال برام بود وردی آیپی کلاد فلر به چه منظوری مجاز شده؟

**Comment by kyochikuto** [comment]
با فرض سناریوی طرح شده در بالا شما همین الان سرورتون رو پشت شبکه ی توزیع کلادفلر قرار داده اید و همین امر مستلزم امکان برقراری ارتباط از طرف کلادفلر به سرور شماست و علت لحاظ این مورد.
