### ISSUE TITLE
حمله از سمت چین

### ISSUE THREAD

**Issue by SalarAbapour** [redpilllabs/GFIProxyProtector#12]
سلام ممنون بایت این اسکریپت زیبا
آیا این اسکریپت از حمله چین به سرورهای ایران هم جلوگیری میکنه؟ آیا عملکردی مطابق توییت زیر داره؟
https://x.com/GhostOfSarina/status/1743218101230186689?s=20

**Comment by kyochikuto** [comment]
بله تا حد زیادی، در مشاهدات خودم اینطور بود که بات های چینی صرفا از آی‌پی چینی استفاده نمیکنند و سرورهای مجازی در شبکه های معتبر خریداری کردند برای این کار اما بستن آی‌پی چین تا حدود زیادی از سرور شما محافظت خواهد کرد، گزینه ای هم برای محافظت از تمام آی‌پی های غیرایرانی قرار گرفته (البته نکته داره که در فایل README بخوانید) که میتونید فعال کنید.
