### ISSUE TITLE
استفاده از ufw برای مسدود کردن دسترسی ها

### ISSUE THREAD

**Issue by ImMohammad20000** [redpilllabs/GFIProxyProtector#13]
سلام 
لطفا امکان استفاده از ufw به جای iptables رو هم برای بستن دسترسی ها فراهم کنید🙏

**Comment by kyochikuto** [comment]
سلام
فکر نمیکنم وقتش رو داشته باشم از طرفی باور دارم افرادی که با ufw آشنا هستند توانایی کار کردن با iptables که قدرتمندتر هستش رو هم دارند.
