### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by dani96102** [redpilllabs/GFIProxyProtector#14]
باتشکر از پروژه خوبتون
لطفا کشور روسیه هم مثل چین اضافه کنید
و اینکه بنظرتون نمیشه یکاری کرد ورودی های ایران هم محدود بشه به ایپی ssh خودمون و آیپی هایی که کانفیگ های پنل v2ray دارن استفاده میکنن یعنی مثلا خودش اتوماتیک از لاگ های پنل ایپی هارو بگیره و بهشون اجازه دسترسی بده و هرچی جز اونا و ssh خودمون هست بن کنه که نتونن با ایپی و از داخل ایران سرور شناسایی کنن یا بهش اتک بزنن

**Comment by kyochikuto** [comment]
>  لطفا کشور روسیه هم مثل چین اضافه کنید

تلاش میکنم اضافه کنم.
> و اینکه بنظرتون نمیشه یکاری کرد ورودی های ایران هم محدود بشه به ایپی ssh خودمون و آیپی هایی که کانفیگ های پنل v2ray دارن استفاده میکنن یعنی مثلا خودش اتوماتیک از لاگ های پنل ایپی هارو بگیره و بهشون اجازه دسترسی بده و هرچی جز اونا و ssh خودمون هست بن کنه که نتونن با ایپی و از داخل ایران سرور شناسایی کنن یا بهش اتک بزنن

پیچیدگی بسیاری داره که از وظایف این اسکریپت خارج هستند.
