### ISSUE TITLE
Add IP ranges of other CDNs

### ISSUE THREAD

**Issue by mmrabbani** [redpilllabs/GFIProxyProtector#15]
Please add IP ranges of other CDNs used by Iranians. It has no side effects on Cloudflare users.
Here are lists of GCore and CloudFront CDN (In amazon json file, you should use CloudFront only)

https://api.gcore.com/cdn/public-ip-list

https://ip-ranges.amazonaws.com/ip-ranges.json

**Comment by kyochikuto** [comment]
تلاش میکنم در آینده اضافه کنم، با تشکر.
