### ISSUE TITLE
اضافه کردن یک آیپی استثنا

### ISSUE THREAD

**Issue by MohammadTtay** [redpilllabs/GFIProxyProtector#16]
چطور یه آیپی رو به شکل استثنا اضافه کنیم که بتونه بسته به سرورمون ارسال کنه ؟
چون فرض مثال توی مرزبان نیازه که نود ها با سرور اصلی در ارتباط باشن و فکر کنم این اسکریپت مشکل ساز میشه

**Comment by kyochikuto** [comment]
از دستور زیر استفاده کنید:

```
iptables -I INPUT -s IP_ADDR -j ACCEPT
```

**Comment by newman222** [comment]
متاسفانه این دستور کار نکرد

**Comment by kyochikuto** [comment]
مجدد امتحان کنید:

```
iptables -I INPUT -p udp -s IP_ADDR -j ACCEPT
iptables -I INPUT -p tcp -s IP_ADDR -j ACCEPT
iptables-save /etc/iptables/rules.v4

```

این در صورتی کار میکنه که آی‌پی کلاینت ثابت باشه.

**Comment by newman222** [comment]
Unknown arguments found on commandline
این پیغام رو میده

**Comment by newman222** [comment]
متاسفانه بعد از فعال کردن گزینه 1 و 2

بعد از چهار روز میزان فیلترینگ ای پی هام چند برابر شده

**Comment by kyochikuto** [comment]
> متاسفانه بعد از فعال کردن گزینه 1 و 2
> 
> بعد از چهار روز میزان فیلترینگ ای پی هام چند برابر شده

از چه پنلی استفاده میکردید؟ لطفا خروجی دستور زیر رو اینجا بفرستید:

```
iptables -L -v -n
```
