### ISSUE TITLE
میزان تاثیر 

### ISSUE THREAD

**Issue by seyyed1332** [redpilllabs/GFIProxyProtector#17]
سلام وقتتون بخیر .. بعد از تقریبا یک روز استفاده با پرتکل Grpc و پنل ثنایی بازم سرورم به صورت کامل شناسایی شد و ایپی بلاک شد 

پیشنهاد شما چه پرتکلی هست که امکان مدیریت رو هم بهمون بده؟ 

و اینک فقط ۲۴ ساعت هم دووم نیاورده مشکل از کجا بوده؟

**Comment by seyyed1332** [comment]
درود بر دوست عزیز .. از بابت دومی مطمعن نیستم ولی منباب سوال اول کانفیگ رو
پابلیک کرده بودم و با این احتساب بعد از بررسی متوجه شدم حدود 2 ترابایت
ریلیتی رد کرده تو همین 2 روز ..

‫‪Kyōchikutō | キョウチクトウ‬‏ ***@***.***‬‏> در تاریخ یکشنبه ۱۴
ژانویه ۲۰۲۴ ساعت ۱۸:۲۴ نوشت:‬

**Comment by kyochikuto** [comment]
این تدابیر برای پروکسی REALITY کاربردی ندارند، دلیل مسدود شدن سرور شما همین بوده.

**Comment by seyyed1332** [comment]
از نظر شما چه پرتکلی پایداری بهتری داره با این تدابیر ؟

**Comment by kyochikuto** [comment]
پروکسی های Hysteria و Websocket و gRPC عملکرد خوبی دارند، از websocket روی یک ورکر هم میتونید بدون نیاز به سرور استفاده کنید.

**Comment by seyyed1332** [comment]
مچکر از پاسخگویی شیواتون حتما بررسی میکنم از اونجایی که من برای پابلیک کردن
استفاده میکنم دنبال یه پرتکل مقاوم هستم میتونید به تلگرامم سر بزنید @seyyed

‫‪Kyōchikutō | キョウチクトウ‬‏ ***@***.***‬‏> در تاریخ دوشنبه ۱۵
ژانویه ۲۰۲۴ ساعت ۲۳:۰۸ نوشت:‬
