### ISSUE TITLE
اضافه کردن ایپی روسیه علاوه بر چین

### ISSUE THREAD

**Issue by MrVb0** [redpilllabs/GFIProxyProtector#20]
سلام وقت بخیر من میخوام فقط ورودی ایپی های روسیه و چین رو بلاک کنه ، امکانش هست لیست ایپی های روسیه هم اضافه کنید ؟

**Comment by kyochikuto** [comment]
اضافه شد، اگر مشکلی بود شاید نیاز به نصب سرور خام داشته باشید.
