### ISSUE TITLE
سرورپیاده سازی

### ISSUE THREAD

**Issue by applesoft2023** [redpilllabs/GFIProxyProtector#23]
سلام استاد

این روزها همه ازتانل استفاده میکنند بنابراین یک سرورخارج ویک سرورایران مورد نیازاست  این دستورات باید در کدام سرور پیاده شود ایران یا خارج ؟
وگزینه سوم این دستور دقیقا کارش چیست چون دستورش با متنش متفاوت است 
گزینه سوم نوشته:
 Block ALL INCOMING except from Iran / Cloudflare
 اماوقتی دستور را میزنیم متنی که می ایداین است:
unblock connections from china!!!
 که عملا با دستور شماره 1 در تضاد است
لطفا راهنمایی بفرمایید

**Comment by kyochikuto** [comment]
این اسکریپت برای سرورهای خارج از ایران تهیه شده. عبارتی که مشاهده میکنید به خاطر فعال کردن ممنوعیت اتصال از چین هستش و وقتی که ایران اکسس میکنید شامل چین هم میشه بنابراین دستورات قبلی حذف و دستورات ایران اکسس اجرا میشوند.
