### ISSUE TITLE
مشکل در دبیان

### ISSUE THREAD

**Issue by saeedpm** [redpilllabs/GFIProxyProtector#3]
سلام این مشکل هنوز هست شاید با سرور یه سری سرور مشکل داشته باشه نمیدونم همه چی نصب میشه ولی وقتی میخاد اجرا و اعمال کنه یه ارور میده و فایل رو پیدا نمیکنه
من اسکرین میزارم تا شما تونستی بررسی کنین.

![image](https://user-images.githubusercontent.com/95865148/229350686-1165e7c2-d421-4ca9-8ca2-3cd33f4dd295.png)

**Comment by 0xNeu** [comment]
سلام دوست عزیز این خطا نیست صرفا جهت اطلاع بعد از اولین اجرا چاپ میشه که اون کتابخانه نصب نیست طبیعتا و اسکریپت قصد داره نصبش کنه. ممکنه رنگ و ادبیات پیغام غلط انداز باشه که تغییرش میدم. با تشکر.

**Comment by saeedpm** [comment]
سلام ممنون از پیگیری - بله درست میگین ولی خب وقتی هرکاری میکنم active نمیشه چیکار کنم 
بعد کمیت تست کردم الان یه مشکل جدید پیش اومده همون اول میخاد نصب کنه به اجبار سرور ریبوت میکنه و نمیزاره نصب ادامه پیدا کنه

**Comment by 0xNeu** [comment]
ریبوت به خاطر نصب هسته ی جدیده و بعد ریبوت دیگه باید هسته ی جدید بارگذاری شده باشه، بعد از ریبوت دوباره اجرا می‌کنید دقیقا چه اتفاقی میوفته؟ پیغام ها و خروجی ها چی هستن؟

**Comment by saeedpm** [comment]
به نظر هسته جدید نصب نمیشه دیگه - به خاطر همین بعد ریبوت باز هی ریبوت میکنه. تو اسکرین قابل مشاهده هست 
![image](https://user-images.githubusercontent.com/95865148/230542689-790963b1-0f14-4646-a5df-be99bbc0c59e.png)

**Comment by 0xNeu** [comment]
آخرین نسخه هسته Stable برای دبیان ۱۱ در حال حاضر 5.10 هستش ولی سرور شما میخواد نسخه 6.1 رو از مخازن Bullesye نصب کنه که طبیعتا موجود نیست و فقط دبیان Sid این هسته رو داره! به نظر میاد سیستم عامل تون Debian Bullesye استاندارد نیست!

از کدوم سرویس دهنده سرور گرفتید؟ موقع ساخت سرور دقیقا عبارتی که برای نام سیستم عامل نوشته بود چی بود؟ گزینه درست باید Debian Bullesye Minimal باشه.
