### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by saveiran2023** [redpilllabs/GFIProxyProtector#8]
سلام وقتتون بخیر
زمانی که اسکریپت رو اجرا می کنم برای فعال کرده مسدودی ایران این ارور رو میده و فعال نمیشه

Getting the latest aggregated database
Converting the CIDR database to binary format...
Can't locate Net/CIDR/Lite.pm in @INC (you may need to install the Net::CIDR::Lite module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /usr/libexec/rainb0w/xt_geoip_build_agg line 9.
BEGIN failed--compilation aborted at /usr/libexec/rainb0w/xt_geoip_build_agg line 9.
xt_geoip               16384  0

Blocking OUTGOING connections to Iran
Could not open /usr/share/xt_geoip/IR.iv4: No such file or directory
iptables v1.8.7 (nf_tables): Could not read geoip database
Could not open /usr/share/xt_geoip/IR.iv6: No such file or directory
ip6tables v1.8.7 (nf_tables): Could not read geoip database
Could not open /usr/share/xt_geoip/IR.iv4: No such file or directory
iptables v1.8.7 (nf_tables): Could not read geoip database
Could not open /usr/share/xt_geoip/IR.iv6: No such file or directory
ip6tables v1.8.7 (nf_tables): Could not read geoip database

**Comment by kyochikuto** [comment]
لطفا نام و نسخه سیستم عامل تون رو بفرمایید.

**Comment by kyochikuto** [comment]
در مشکل شماره #9برطرف شد.
