### ISSUE TITLE
باگ Deactivated

### ISSUE THREAD

**Issue by darklies** [redpilllabs/GFIProxyProtector#9]
![image](https://github.com/redpilllabs/GFIProxyProtector/assets/48620197/f3eadf00-0757-4ec8-830b-5104a29f54cd)
اوبونتو 20 
 BBRv3 using xanmod kernel 
نصبه رو سرور

تحت هر شرایطی این deactivated میزنه

**Comment by kyochikuto** [comment]
دستورهای زیر چه نتیجه ای دارند:

```
sudo apt install xtables-addons-dkms
sudo apt install xtables-addons-common
```

**Comment by meower1** [comment]
سلام داداش گل. مشکل مشابه رو دارم سیستم عاملمم همون ubuntu 20 هست. بعده فعال سازی گزینه 1 و 2 وضعیت رو همچنان deactivated میزنه 
خروجیه دوتا دستور بالا هم اینه که نصب شدن و ارور خاصی هنگام اجرا نداشتم

**Comment by kyochikuto** [comment]
این دستورات رو هم امتحان کنید و ریبوت کنید:
‍‍```
sudo apt install module-assistant xtables-addons-source
sudo module-assistant auto-install xtables-addons-source
```

**Comment by meower1** [comment]
دستور دوم به مشکل بر میخوره
<img width="656" alt="image" src="https://github.com/redpilllabs/GFIProxyProtector/assets/109747197/09451a79-ecf0-41d4-85a8-ef1701a38ef6">

لاگ ارورش 
<img width="748" alt="image" src="https://github.com/redpilllabs/GFIProxyProtector/assets/109747197/79058b15-2b3d-45c7-8b0a-9852eaf137c4">

**Comment by kyochikuto** [comment]
روی یک سرور تازه نصب امتحان کنید لطفا ترجیحا اوبونتو ۲۲ این رو هم خاطرنشان کنم اگر از پروکسی reality استفاده میکنید این اسکریپت کمکی نمیکنه چون کاوشگرهای این پروکسی از ای پی ایران میان.

**Comment by darklies** [comment]
> sudo apt install xtables-addons-common

![image](https://github.com/redpilllabs/GFIProxyProtector/assets/48620197/f4a70413-af71-4cc4-9dd2-790dd6126cef)

**Comment by darklies** [comment]
> sudo module-assistant auto-install xtables-addons-source

![image](https://github.com/redpilllabs/GFIProxyProtector/assets/48620197/58827baf-19e8-44f0-a75b-8ead1821f3c8)

**Comment by kyochikuto** [comment]
از آنجا که روش های بکار گرفته در این اسکریپت در مقابل کاوشگر های پروتکل ریالیتی کاربرد ندارند و من هم درگیر پروژه های دیگری هستم توصیه میکنم به دنبال روش های محافظتی دیگری برای سرورها باشید. با عرض پوزش و آرزوی موفقیت و آزادی ایران.

**Comment by kyochikuto** [comment]
گویا این مشکل از دستور  غلط  curl برای دریافت کتابخانه نشات گرفته و همچنین سایر اسکریپت های Rainb0w رو هم تحت تاثیر قرار داده بود. مخزن رو از آرشیو خارج کردم و اصلاحیه بر روی اسکریپت اعمال شد و هم اکنون میتونید ازش دوباره استفاده کنید. پیروز باشید.
